Release version 'Redefined 1.1'

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,6 +1,6 @@
 #!/sbin/sh
 # My Charging Controller
-# mcc Install (201807271)
+# mcc Install Script
 # JayminSuthar @ xda-developers
 
 # Copyright (c) 2018 Jaymin Suthar. All rights reserved.
@@ -10,7 +10,7 @@
 # mcc is released under the terms of the GNU GPL v3, as been
 ## published by the Free Software Foundation. And permission
 ## hereby is granted to use, modify or redistribute it maybe
-# partially or entirely under GPLv3 only.
+## partially or entirely under GPLv3 only.
 
 # mcc was written in a hope of being useful. And any kind of
 ## warranty is not provided. See GPLv3 for details.
@@ -18,35 +18,47 @@
 # You should already have received a copy of GPLv3 with mcc,
 ## if not, see <http://www.gnu.org/licenses/>.
 
-out_fd=/proc/self/fd/$2;
-zip_path="$3";
-tmp_dir=/dev/tmp_$$;
-cfg_path_tmp=$tmp_dir/mcc.conf;
+out_fd=$2;
+boot_mode=false;
+system=/system;
+tmp_dir=/dev/mcc_$$;
+log_dir=$tmp_dir/log;
+zip_dir=$tmp_dir/zip;
+bin_dir=$zip_dir/bin;
+sys_dir=$zip_dir/system;
+bb_path=$bin_dir/busybox;
+cfg_path=$zip_dir/mcc.conf;
+copy_path=$zip_dir/COPYING;
+help_path=$zip_dir/README.md;
 
-if (! echo "$(ps -A 2>/dev/null || ps)" | grep -v grep | grep zygote >/dev/null); then
-  boot_mode=false;
-else
-  boot_mode=true;
+umask 022;
+mkdir -p $log_dir;
+if [ "$1" != --skip-errors ]; then
+  exec $0 --skip-errors $2 "$3" 2>$log_dir/install_err.log;
 fi;
+set -x 2>$log_dir/install.log;
 
-if (! $boot_mode); then
+if (! echo "$(ps -A || ps)" | grep -v grep | grep zygote >/dev/null); then
   mount -o bind /dev/urandom /dev/random;
-  if (readlink /proc/$$/fd/$2 2>/dev/null | grep /tmp >/dev/null); then
-    for fd in /proc/$$/fd/*; do
-      if (readlink $fd 2>/dev/null | grep pipe >/dev/null); then
+  fd_dir=/proc/$$/fd;
+  if (readlink $fd_dir/$out_fd | grep /tmp >/dev/null); then
+    for fd in $fd_dir/*; do
+      if (readlink $fd | grep pipe >/dev/null); then
         fd=${fd##*/};
         if (ps | grep -v grep | grep " 3 $fd " >/dev/null); then
-          out_fd=/proc/self/fd/$fd;
+          out_fd=$fd;
           break;
         fi;
       fi;
     done;
   fi;
+else
+  boot_mode=true;
 fi;
 
 ui_print() {
   if (! $boot_mode); then
-    echo -e "ui_print $1\nui_print" >>$out_fd;
+    echo -e "ui_print $1\nui_print" >>/proc/self/fd/$out_fd;
   else
     echo "$1";
   fi;
@@ -55,100 +67,82 @@ ui_print() {
 abort() {
   ui_print ' ';
   print --error "$1";
-  cleanup;
+  cleanup --error;
   exit 1;
 }
 
 print() {
-  if [ "$1" == --error ]; then
-    ui_print "FATAL ERROR: $2";
-  else
-    ui_print "INFO: $1";
-  fi;
+  case "$1" in
+    --error) ui_print "FATAL ERROR: $2"; ;;
+    --done)  ui_print '- Done';          ;;
+    *)       ui_print "INFO: $1";        ;;
+  esac;
 }
 
 cleanup() {
+  log_dir_final=/dev/mcc_logs;
 
-  umount $mount_dir 2>/dev/null;
-  losetup -d $loopdev_path 2>/dev/null;
-  rm -r $tmp_dir $mcc_dir $main_path $init_path 2>/dev/null;
+  if [ "$1" == --error ]; then rm -r $mcc_dir $main_path $init_path; fi;
+  if (umount $mount_dir); then losetup -d $loop_path; fi;
+  rm -r $tmp_dir;
 
   if (! $boot_mode); then
-    for mounted in /system /vendor /dev/random; do
-      if (! umount $mounted 2>/dev/null); then umount -l $mounted; fi;
+    for mounted in /data /system /vendor /dev/random; do
+      umount -l $mounted;
     done;
   fi;
+  mkdir $log_dir_final;
+  cp -rf $log_dir/. $log_dir_final/;
 }
 
 is_mounted() {
-  cat /proc/mounts | grep " $1 " >/dev/null;
+  grep -q " $1 " /proc/mounts;
 }
 
 mount_for_ab() {
 
-  if (is_mounted "$2"); then
-    if (! umount "$2"); then return 1; fi;
+  if (is_mounted /$1); then return; fi;
+
+  device_path=$(find /dev/block -iname $1$slot | head -n 1);
+  device_path=$(readlink $device_path || echo $device_path);
+
+  if (! mount -t auto -o ro $device_path /$1); then
+    abort "Failed to mount /$1";
   fi;
-
-  device_path=$(find /dev/block -iname $1$slot 2>/dev/null | head -n 1);
-  device_path=$(readlink $device_path 2>/dev/null || echo $device_path);
-
-  mount -t ext4 -o ro $device_path "$2" 2>/dev/null || \
-  mount -t ext4 -o ro,remount $device_path "$2";
-  return $?;
 }
 
-get_prop() { 
-  cat "$2" | grep -m 1 "^$1=" | cut -d= -f2;
-}
-
-get_imgsize() {
-  case $1 in
-    --total) field=2; ;;
-    --used)  field=1; ;;
-  esac;
-  blocks=$(e2fsck -n $img_path | grep -Eo '[0-9]+/[0-9]+ blocks' | cut -d/ -f$field | cut -d' ' -f1);
-  echo $(((blocks + 255) / 256));
+get_prop() {
+  sed -n "s/^$1=//p" $2;
 }
 
 set_prop() {
-  local tmp_path=$tmp_dir/tmp;
-
-  while read -r line; do
-    if (echo "$line" | grep "^$1=" >/dev/null); then
-      echo "$1=$2" >>$tmp_path;
-    else
-      echo "$line" >>$tmp_path;
-    fi;
-  done <"$3";
-  mv -f $tmp_path "$3";
+  sed -i "s|^$1=.*|$1=$2|" $3;
 }
 
 set_perm() {
-  if (! chown $2:$3 "$1" 2>/dev/null); then chown $2.$3 "$1"; fi;
-  chmod $4 "$1";
+  chown $2:$3 $1;
+  chmod $4 $1;
   if [ -z "$5" ]; then
-    chcon u:object_r:system_file:s0 "$1";
+    chcon u:object_r:system_file:s0 $1;
   else
-    chcon "$5" "$1";
+    chcon $5 $1;
   fi;
 }
 
 set_perm_recursive() {
-  find "$1" 2>/dev/null | while read -r entry; do
-    if [ -d "$entry" ]; then
-      set_perm "$entry" $2 $3 $4 "$6";
+  find $1 | while read -r entry; do
+    if [ -d $entry ]; then
+      set_perm $entry $2 $3 $4 $6;
     else
-      set_perm "$entry" $2 $3 $5 "$6";
+      set_perm $entry $2 $3 $5 $6;
     fi;
   done;
 }
 
 restore_cfg() {
-  if [ -f $cfg_path_tmp ]; then
-    print 'Restoring old config...';
+  if cfg_path_bak=$(ls $tmp_dir/mcc.conf); then
     for prop in auto_switch auto_power thr_disable thr_enable thr_power; do
-      set_prop $prop $(get_prop $prop $cfg_path_tmp) $cfg_path $mcc_dir/mcc.conf;
+      set_prop $prop $(get_prop $prop $cfg_path_bak) $cfg_path_mcc;
     done;
   fi;
 }
@@ -160,8 +154,6 @@ warn_for_system_install() {
   ui_print '************************************************************';
   ui_print '            Failed to detect support for Magisk             ';
   ui_print '************************************************************';
-  ui_print '        Forcing a system installation as a fallback         ';
-  ui_print '************************************************************';
   ui_print ' ';
 }
 
@@ -169,69 +161,44 @@ ui_print ' ';
 ui_print '************************************************************';
 ui_print '                  My Charging Controller                    ';
 ui_print '************************************************************';
-ui_print '     mcc is developed and copyrighted by Jaymin Suthar      ';
-ui_print '************************************************************';
 ui_print ' ';
 
+print 'Unzipping files...';
+unzip -o "$3" '*' -d $zip_dir >/dev/null;
+if [ ! -f $bb_path ]; then abort 'Failed to unzip files'; fi;
+
 print 'Preparing environment, mounts...';
-umask 022;
 
-if (! which unzip >/dev/null); then abort 'Failed to find unzip'; fi;
+chmod 0755 $bb_path;
+if (! $bb_path --install $bin_dir/); then
+  abort 'Only arm-based CPUs are supported';
+fi;
+export PATH=$bin_dir:$PATH;
+
+if ! slot=$(get_prop androidboot.slot_suffix /proc/cmdline); then
+  if slot=$(get_prop androidboot.slot        /proc/cmdline); then
+    slot=_$slot;
+  fi;
+fi;
+
 if (! is_mounted /data); then
-  if (! mount /data 2>/dev/null); then
-    if (! mount -o rw,remount /data); then abort 'Failed to mount /data'; fi;
-  fi;
+  if (! mount /data); then abort 'Failed to mount /data'; fi;
 fi;
+for mount_it in /system /vendor; do mount -o ro $mount_it; done;
 
-if (! slot=$(get_prop androidboot.slot_suffix /proc/cmdline 2>/dev/null)); then
-  if (slot=$(get_prop androidboot.slot /proc/cmdline)); then slot=_$slot; fi;
-fi;
+if [ -n "$slot" ]; then mount_for_ab system; fi;
+if [ -f $system/init.rc ]; then system=$system/system; fi;
+if [ -L $system/vendor ]; then mount_for_ab vendor; fi;
 
-print 'Mounting /system, /vendor (ro)...';
-if [ -n "$slot" ]; then
-
-  print "A/B slot scheme detected, using: $slot";
-  if (! mount_for_ab system /system); then
-    mount_for_ab system_root /system;
-  fi;
-  if [ -f /system/init.rc ]; then
-    print 'system_root image scheme detected';
-    system=/system/system;
-  else
-    system=/system;
-  fi;
-  if [ -L $system/vendor ]; then mount_for_ab vendor /vendor; fi;
-
-else
-  for mount_it in /system /vendor; do
-    if (! mount -o ro $mount_it 2>/dev/null); then
-      mount -o ro,remount $mount_it;
-    fi;
-  done;
-fi;
-
-if (! is_mounted /system); then
-  abort 'Failed to mount /system';
-elif [ -L $system/vendor ]; then
-  if (! is_mounted /vendor); then abort 'Failed to mount /vendor'; fi;
-fi;
-
-abi_long=$(get_prop ro.product.cpu.abi $system/build.prop);
-
-if (echo $abi_long | grep arm >/dev/null); then
-  arch=arm;
-else
-  arch=x86;
-fi;
 if (! $boot_mode); then
-  if (echo $abi_long | grep -E 'arm64|x86_64' >/dev/null); then
+  if (get_prop ro.product.cpu.abi $system/build.prop | grep -q arm64); then
     export LD_LIBRARY_PATH=$system/lib64:$system/vendor/lib64;
   else
     export LD_LIBRARY_PATH=$system/lib:$system/vendor/lib;
   fi;
 fi;
 
-print 'Detecting Magisk support...';
+print 'Do you have Magisk installed ??';
 
 if [ -d /data/adb/magisk ]; then
   magisk_mode=true;
@@ -253,50 +220,35 @@ if ($magisk_mode && [ ! -f $func_path ]); then warn_for_system_install; fi;
 if ($magisk_mode); then
   mount_dir=$tmp_dir/img;
   mcc_dir=$mount_dir/mcc;
-  bin_dir=$mcc_dir/bin;
   doc_dir=$mcc_dir/docs;
-  sys_dir=$mcc_dir/system;
-  bb_path=$bin_dir/busybox;
-  cfg_path=$mcc_dir/mcc.conf;
+  bin_dir_mcc=$mcc_dir/bin;
+  sys_dir_mcc=$mcc_dir/system;
+  cfg_path_mcc=$mcc_dir/mcc.conf;
 
   if ($boot_mode); then img_path=${img_path%/*}/magisk_merge.img; fi;
 
   if [ $(get_prop MAGISK_VER_CODE $func_path) -lt 1400 ]; then
-    abort 'Upgrade to Magisk >= 1400 to use mcc';
+    abort 'Magisk >= 1400 is required';
   fi;
 
-  print 'Installing mcc...';
+  print 'Installing (Magisk)...';
 
-  mkdir -p $mount_dir;
-  if [ -f $img_path ]; then
-
-    e2fsck -p -f $img_path >/dev/null;
-
-    img_total=$(get_imgsize --total);
-    img_used=$(get_imgsize --used);
-
-    if [ $img_total -eq $img_used ]; then
-      print "Expanding $img_path...";
-      resize2fs $img_path $((img_total + 32))M >/dev/null;
-    fi;
-  else
-    print "Creating $img_path...";
+  mkdir $mount_dir;
+  if [ ! -f $img_path ]; then
     if (! make_ext4fs -l 64M $img_path >/dev/null); then
       $system/bin/mke2fs -t ext4 $img_path 64M >/dev/null;
     fi;
   fi;
 
   print "Mounting $img_path...";
-
   for minor in 0 1 2 3 4 5 6 7; do
-    loopdev_path=/dev/block/loop$minor;
+    loop_path=/dev/block/loop$minor;
 
-    if [ ! -f $loopdev_path ]; then
-      if [ ! -b $loopdev_path ]; then mknod $loopdev_path b 7 $minor; fi;
-    fi;
-    if (losetup $loopdev_path $img_path >/dev/null 2>&1); then
-      if (mount -t ext4 -o rw,noatime $loopdev_path $mount_dir 2>/dev/null || \
-          mount -t ext4 -o rw,loop $loopdev_path $mount_dir); then
+    if [ ! -b $loop_path ]; then mknod $loop_path b 7 $minor; fi;
+
+    if (losetup $loop_path $img_path >/dev/null); then
+      if (mount -t ext4 -o rw,noatime $loop_path $mount_dir || \
+          mount -t ext4 -o rw,loop    $loop_path $mount_dir); then
         break;
       fi;
     fi;
@@ -304,76 +256,70 @@ if ($magisk_mode); then
   if (! is_mounted $mount_dir); then abort "Failed to mount $img_path"; fi;
 
   if ($boot_mode); then
-    cp $mcc_dir_boot/mcc.conf $tmp_dir/ 2>/dev/null;
+    cp $mcc_dir_boot/mcc.conf $tmp_dir/;
   else
-    cp $cfg_path $tmp_dir/ 2>/dev/null;
+    cp $cfg_path_mcc $tmp_dir/;
   fi;
-  rm -r $mcc_dir 2>/dev/null;
-  mkdir -p $doc_dir $mcc_dir/log;
+  rm -r $mcc_dir;
+  mkdir -p $doc_dir $sys_dir_mcc $bin_dir_mcc $mcc_dir/log;
 
-  print 'Unzipping mcc files...';
-  unzip -o "$zip_path" 'system/*' bin/busybox_$arch mcc.conf post-fs-data.sh service.sh module.prop -d $mcc_dir >/dev/null;
-  unzip -o "$zip_path" COPYING README.md -d $doc_dir >/dev/null;
+  print 'Copying required files...';
+  cp -r $sys_dir/.                                              $sys_dir_mcc/;
+  cp -r $bin_dir/.                                              $bin_dir_mcc/;
+  cp    $cfg_path $zip_dir/post-fs-data.sh $zip_dir/module.prop $mcc_dir/;
+  cp    $copy_path $help_path                                   $doc_dir/;
 
   restore_cfg;
-  print 'Setting up...';
-  rm -r $sys_dir/etc;
-  mv ${bb_path}_* $bb_path;
-  if [ ! -d $system/xbin ]; then mv $sys_dir/xbin $sys_dir/bin; fi;
+
+  rm -r $sys_dir_mcc/etc;
+  if [ ! -d $system/xbin ]; then mv $sys_dir_mcc/xbin $sys_dir_mcc/bin; fi;
 
   touch $mcc_dir/auto_mount;
   if ($boot_mode); then
-    mkdir $mcc_dir_boot 2>/dev/null;
+    mkdir $mcc_dir_boot;
     touch $mcc_dir_boot/update;
     cp -f $mcc_dir/module.prop $mcc_dir_boot/;
   fi;
 
   print 'Setting permissions...';
-  set_perm_recursive $mcc_dir      0    0 0755 0644;
-  set_perm_recursive $sys_dir/*bin 0 2000 0755 0755;
-  set_perm           $bb_path      0 2000 0755;
+  set_perm_recursive $mcc_dir             0 0    0755 0644;
+  set_perm_recursive $sys_dir_mcc/*bin    0 2000 0755 0755;
+  set_perm           $bin_dir_mcc/busybox 0 2000 0755;
 
 else
   mcc_dir=/data/adb/mcc;
-  bin_dir=$mcc_dir/bin;
   doc_dir=$mcc_dir/docs;
-  bb_path=$bin_dir/busybox;
-  main_path=$system/bin/mcc;
-  init_path=$system/etc/init.d/mcc_launcher;
+  init_dir=$system/etc/init.d;
+  main_path=$system/xbin/mcc;
+  init_path=$init_dir/mcc_launcher;
+  bin_dir_mcc=$mcc_dir/bin;
+  cfg_path_mcc=$mcc_dir/mcc.conf;
 
-  root=${system%/*};
-  if [ -z "$root" ]; then root=/; fi;
-
-  if [ ! -d ${init_path%/*} ]; then
-    ui_print ' ';
-    print --error 'Failed to detect init.d support';
-    abort "Please check 'Init.d Injector' for this";
+  if [ ! -d $init_dir ]; then
+    abort "Use 'Init.d Injector' for init.d support";
   fi;
 
-  print 'Installing mcc...';
+  print 'Installing (system)...';
 
-  mv $mcc_dir/mcc.conf $tmp_dir/ 2>/dev/null;
-  rm -r $mcc_dir 2>/dev/null;
-  mkdir -p $doc_dir $mcc_dir/log;
+  mv $cfg_path_mcc $tmp_dir/;
+  rm -r $mcc_dir;
+  mkdir -p $doc_dir $bin_dir_mcc $mcc_dir/log;
 
-  print 'Unzipping mcc files...';
-  unzip -o "$zip_path" 'system/*' -d $root >/dev/null;
-  unzip -o "$zip_path" bin/busybox_$arch mcc.conf -d $mcc_dir >/dev/null;
-  unzip -o "$zip_path" COPYING README.md -d $doc_dir >/dev/null;
+  print 'Copying required files...';
+  cp -rf $sys_dir/.            $system/;
+  cp -r  $bin_dir/.            $bin_dir_mcc/;
+  cp     $cfg_path             $mcc_dir/;
+  cp     $copy_path $help_path $doc_dir/;
 
   restore_cfg;
-  print 'Setting up...';
-  mv ${bb_path}_* $bb_path;
-  mv -f $system/xbin/mcc $main_path;
-  if [ -z "$(ls $system/xbin)" ]; then rm -r $system/xbin; fi;
 
   print 'Setting permissions...';
-  set_perm_recursive $mcc_dir   0    0 0700 0600 u:object_r:adb_data_file:s0;
-  set_perm           $bb_path   0 2000 0710      u:object_r:adb_data_file:s0;
-  set_perm           $main_path 0 2000 0755;
-  set_perm           $init_path 0    0 0755;
+  set_perm_recursive $mcc_dir               0 0    0700 0600 u:object_r:adb_data_file:s0;
+  set_perm           $bin_dir_mcc/busybox   0 2000 0710      u:object_r:adb_data_file:s0;
+  set_perm           $main_path             0 2000 0755;
+  set_perm           $init_path             0 0    0755;
 fi;
 
 cleanup;
-ui_print '- Done';
+print --done;
 exit 0;
diff --git a/system/xbin/mcc b/system/xbin/mcc
--- a/system/xbin/mcc
+++ b/system/xbin/mcc
@@ -1,6 +1,6 @@
 #!/system/bin/sh
 # My Charging Controller
-# mcc Main (201807271)
+# mcc Core/Main Script
 # JayminSuthar @ xda-developers
 
 # Copyright (c) 2018 Jaymin Suthar. All rights reserved.
@@ -18,13 +18,12 @@
 # You should already have received a copy of GPLv3 with mcc,
 ## if not, see <http://www.gnu.org/licenses/>.
 
-mcc_dir=/data/adb/mcc;
+mcc_dir=/data/adb/mcc
 log_dir=$mcc_dir/log;
 bin_dir=$mcc_dir/bin;
-doc_dir=$mcc_dir/docs;
-cfg_path=$mcc_dir/mcc.conf;
 lock_path=$mcc_dir/lock;
-help_path=$doc_dir/README.md;
+cfg_path=$mcc_dir/mcc.conf;
+help_path=$mcc_dir/docs/README.md;
 
 abort() {
   echo ' ';
@@ -42,19 +41,19 @@ print() {
 }
 
 if (! id | grep uid=0 >/dev/null); then
-  su -c mcc "$@";
-  exit;
-fi;
-if ([ ! -d $mcc_dir ] || [ ! -x $bin_dir/busybox ]); then
+  abort 'mcc requires a root shell';
+elif ([ ! -d $mcc_dir ] || [ ! -x $bin_dir/awk ]); then
   abort 'There was an internal error';
+elif [ -f $lock_path ]; then
+  abort 'mcc execution is blocked';
 fi;
+
 if [ -z "$skip_mcc_detach" ]; then
-  skip_mcc_detach=true mcc "$@" &
+  (skip_mcc_detach=true mcc "$@" &);
   exit;
 elif [ -z "$disable_mcc_logs" ]; then
   if [ -z "$skip_mcc_errors" ]; then
-    skip_mcc_errors=true mcc "$@" 2>$log_dir/main_err.log;
-    exit;
+    skip_mcc_errors=true exec mcc "$@" 2>$log_dir/main_err.log;
   else
     set -x 2>$log_dir/main.log;
   fi;
@@ -63,16 +62,15 @@ fi;
 export PATH=$bin_dir:$PATH;
 
 get_prop() {
-  if [ ! -f "$2" ]; then
-    prop_path=$cfg_path;
-  else
-    prop_path="$2";
-  fi;
-  sed -n "s/^$1=//p" $prop_path;
+  sed -n "s/^$1=//p" $(ls "$2" || echo $cfg_path);
 }
 
 set_prop() {
   sed -i "s|^$1=.*|$1=$2|" $cfg_path;
+}
+
+get_event() {
+  get_prop POWER_SUPPLY_$1 $(uevent_f);
 }
 
 auto_switch() {
@@ -104,14 +102,14 @@ uevent_f() {
 }
 
 batt_level() {
-  get_prop POWER_SUPPLY_CAPACITY $(uevent_f);
+  get_event CAPACITY;
 }
 
 is_charging() {
-  if [ "$1" == --ck-current ]; then
-    test $(get_prop POWER_SUPPLY_CURRENT_NOW $(uevent_f)) -le 0;
+  if [ "$1" != --ck-current ]; then
+    get_event STATUS | grep -q '^[Cc]harging$';
   else
-    grep -q '^POWER_SUPPLY_STATUS=[Cc]harging$' $(uevent_f);
+    test $(get_event CURRENT_NOW) -le 0;
   fi;
 }
 
@@ -125,16 +123,17 @@ is_belonging() {
   fi;
 }
 
+is_number() {
+  echo $1 | grep -Eq '^[0-9]+$';
+}
+
 is_bounded() {
   is_belonging $1 1 99;
 }
 
 is_level() {
-  if [ ! $1 -eq $1 ]; then
-    abort "$1 is not a valid number";
-  else
-    is_bounded $1;
-  fi;
+  if (! is_number $1); then abort "$1 is not a number"; fi;
+  is_bounded $1;
 }
 
 write_() {
@@ -156,7 +155,7 @@ write_() {
 
 switch_() {
 
-  if [ ! $1 -eq $1 ]; then
+  if (! is_number $1); then
     case $1 in
       ON)
         inv_stat=OFF;
@@ -169,64 +168,67 @@ switch_() {
     esac;
 
     if (eval $test); then
-      switched=false;
-    elif (! $switched && eval "$test --ck-current"); then
+      switch=true;
+    elif ($switch && eval "$test --ck-current"); then
       write_ $inv_stat;
       sleep 0.3;
     else
-      switched=true;
+      switch=false;
     fi;
-    if (! $switched); then write_ $1; fi;
+    if ($switch); then write_ $1; fi;
 
   else
     get_prop switch_$1;
   fi;
 }
 
+have_daemon() {
+  if (! is_runningd); then abort 'The mcc daemon is not running'; fi;
+}
+
 toggle() {
-  if ($($1)); then
-    val_new=false;
-    stat_new=OFF;
-  else
+  if (! $($1)); then
     val_new=true;
     stat_new=ON;
+
+    have_daemon;
+    reconfigure;
+  else
+    val_new=false;
+    stat_new=OFF;
   fi;
+  print "Toggling $2 $stat_new...";
   set_prop $1 $val_new;
-  print "$2 has been toggled $stat_new";
+  print --done;
 }
 
 charge() {
   case $1 in
-    --enable)
-      key_init=enable;
-      text=enabled;
-    ;;
-    --disable)
-      key_init=disable;
-      text=disabled;
-    ;;
+    --enable)  key_init=enable;  ;;
+    --disable) key_init=disable; ;;
   esac;
+  text=${key_init}d;
 
-  if (! is_runningd); then
-    abort 'The mcc daemon is not running';
-  elif [ $(switch_do) != default ]; then
-    abort 'Another mcc task is already running';
+  have_daemon;
+  if [ $(switch_do) != default ]; then
+    abort 'Another task is already running';
   fi;
 
   reconfigure;
   if (echo $2 | grep -Eq '^[0-9]+%$'); then
 
-    dest_level=$(echo $2 | tr -d %);
+    end_level=$(echo $2 | tr -d %);
 
-    is_bounded $dest_level;
-    print "Charging $text until ${dest_level}%";
+    is_bounded $end_level;
+
+    print "Keep charging $text until ${end_level}%...";
     set_prop switch_do $key_init;
-    while [ $(batt_level) -ne $dest_level ]; do sleep 1; done;
+    while [ $(batt_level) -ne $end_level ]; do sleep 1; done;
 
   elif (echo $2 | grep -Eq '^[0-9]+[smh]?$'); then
 
+    print "Keep charging $text for $2...";
     set_prop switch_do $key_init;
-    print "Charging $text for $2";
     sleep $2;
 
   else
@@ -253,14 +255,14 @@ reconfigure() {
     fi;
   fi;
 
-  for i in 1 2; do set_prop switch_$i dummySwitch; done;
+  print 'Reconfiguring (low level)...';
 
-  print 'Reconfiguring (low_level)...';
+  for i in 1 2; do set_prop switch_$i dummySwitch; done;
   find /sys/devices /sys/module -type f -name uevent >$cache_path;
 
   i=1;
   while read -r main_events; do
-    if (grep -q '^POWER_SUPPLY_NAME=.*[Bb]att.*' $main_events); then
+    if (grep -q '^POWER_SUPPLY_NAME=.*[Bb]att' $main_events); then
       set_prop uevent $main_events;
 
       while read -r chg_events; do
@@ -315,21 +317,20 @@ reconfigure() {
       done <$cache_path;
     fi;
   done <$cache_path;
-  rm $cache_path;
 
-  if [ $i -eq 2 ]; then
-    print --done;
-    print --warn 'A reboot is recommended to prevent conflicts';
-  else
+  if [ $i -eq 1 ]; then
     set_prop uevent dummyEvents;
     abort 'Failed to reconfigure';
+  else
+    print --done;
+    print --warn 'A reboot is recommended to prevent conflicts';
   fi;
   return 0;
 }
 
 if [ "$1" == --force ]; then
-  if ([ "$2" != --switch ] && [ "$2" != --power ]); then
-    abort 'Invalid arguments';
+  if (! echo "$2" | grep -Eq '^(--switch|--power)$'); then
+    abort 'Invalid argument(s)';
   fi;
   enforce=true;
   shift;
@@ -339,9 +340,12 @@ fi;
 
 case $1 in
   --switch)
+    if (echo $# | grep -Eq '^(2|3)$'); then abort 'Invalid argument(s)'; fi;
+
+    print 'Processing/setting thresholds...';
     if [ $# -eq 2 ]; then
 
-      is_level "$2";
+      is_level $2;
       if (! $enforce); then is_belonging $2 20 85; fi;
 
       if [ $2 -ge 25 ]; then
@@ -359,8 +363,8 @@ case $1 in
 
     elif [ $# -eq 3 ]; then
 
-      is_level "$2";
-      is_level "$3";
+      is_level $2;
+      is_level $3;
 
       if [ $2 -le $3 ]; then
         abort "$2 is not > $3";
@@ -369,19 +373,18 @@ case $1 in
         is_belonging $3 15 85;
         if [ $2 -lt $(($3 + 5)) ]; then abort "$2 is too close to $3"; fi;
       fi;
-
-    else
-      abort 'Invalid arguments';
     fi;
+
     set_prop thr_disable $thr_disable $2;
     set_prop thr_enable  $thr_enable  $3;
     print --done;
   ;;
 
   --power)
-    if [ $# -ne 2 ]; then abort 'Invalid arguments'; fi;
+    if [ $# -ne 2 ]; then abort 'Invalid argument(s)'; fi;
 
-    is_level "$2";
+    print 'Processing/setting threshold...';
+    is_level $2;
     if (! $enforce); then is_belonging $2 5 20; fi;
 
     set_prop thr_power $2;
@@ -389,8 +392,9 @@ case $1 in
   ;;
 
   --revert)
-    if [ $# -gt 1 ]; then abort 'Invalid arguments'; fi;
+    if [ $# -gt 1 ]; then abort 'Invalid argument(s)'; fi;
 
+    print 'Reverting thresholds...';
     set_prop thr_disable 80;
     set_prop thr_enable  70;
     set_prop thr_power   20;
@@ -400,63 +404,61 @@ case $1 in
   --toggle)
     shift;
     case $1 in
-      --switch)
-        if (! $(auto_switch)); then
-          if (! is_runningd); then abort 'The mcc daemon is not running'; fi;
-          reconfigure;
-        fi;
-        toggle auto_switch 'Auto Switch';
-      ;;
-      --power)
-        if (! $(auto_power)); then
-          if (! is_runningd); then abort 'The mcc daemon is not running'; fi;
-          reconfigure;
-        fi;
-        toggle auto_power 'Auto Power';
-      ;;
+      --switch) toggle auto_switch 'Auto Switch'; ;;
+      --power)  toggle auto_power  'Auto Power';  ;;
+
       --revert)
-        if (! is_runningd); then abort 'The mcc daemon is not running'; fi;
+        have_daemon;
         reconfigure;
+        print 'Reverting Auto Switch/Power...';
         set_prop auto_switch true;
         set_prop auto_power  true;
         print --done;
       ;;
-      *) abort 'Invalid arguments'; ;;
+      *) abort 'Invalid argument(s)'; ;;
     esac;
   ;;
 
   --enable)
-    if [ $# -ne 2 ]; then abort 'Invalid arguments'; fi;
+    if [ $# -ne 2 ]; then abort 'Invalid argument(s)'; fi;
     charge --enable $2;
   ;;
 
   --disable)
-    if [ $# -ne 2 ]; then abort 'Invalid arguments'; fi;
+    if [ $# -ne 2 ]; then abort 'Invalid argument(s)'; fi;
     charge --disable $2;
   ;;
 
   --cleanup)
+    if [ $# -gt 1 ]; then abort 'Invalid argument(s)'; fi;
+
+    print 'Cleaning...';
     for pid in $(ps | grep -v grep | grep '{mcc}' | grep -v $$ | awk '{ print $1 }'); do
       kill -9 $pid;
     done;
-    rm -f $lock_path;
     set_prop switch_do default;
     print --done;
   ;;
 
   --redaemon)
+    if [ $# -gt 1 ]; then abort 'Invalid argument(s)'; fi;
     if (is_runningd); then abort 'The mcc daemon is already there'; fi;
 
     reconfigure;
+    print 'Launching the mcc daemon...';
     disable_mcc_logs=true mcc --launch-daemon </dev/null >/dev/null 2>&1;
+    sleep 0.5;
     if (! is_runningd); then abort 'Failed to relaunch the daemon'; fi;
     print --done;
   ;;
 
   --launch-daemon)
-    switched=false;
-    revert_ext=false;
-    last_stat=default;
+    switch=true;
+    revert=false;
+    stat_saved=default;
+
+    if [ $# -gt 1 ]; then abort 'Invalid argument(s)'; fi;
+    if (is_runningd); then abort 'Could you rather use [--redaemon] ??'; fi;
 
     while (:); do
       while (! reconfigure --no-action || [ -f $lock_path ]); do
@@ -472,27 +474,27 @@ case $1 in
         default)
           if ($(auto_switch)); then
             if [ $(batt_level) -ge $(thr_disable) ]; then
-              last_stat=OFF;
+              stat_saved=OFF;
               switch_ OFF;
 
             elif [ $(batt_level) -le $(thr_enable) ]; then
-              last_stat=ON;
+              stat_saved=ON;
               switch_ ON;
 
-            elif ($revert_ext); then
-              if [ $last_stat != default ]; then
-                switch_ $last_stat;
-                if ($switched); then revert_ext=false; fi;
+            elif ($revert); then
+              if [ $stat_saved != default ]; then
+                switch_ $stat_saved;
+                if (! $switch); then revert=false; fi;
               fi;
             fi;
           fi;
         ;;
         disable)
-          revert_ext=true;
+          revert=true;
           switch_ OFF;
         ;;
         enable)
-          revert_ext=true;
+          revert=true;
           switch_ ON;
         ;;
       esac;
@@ -501,21 +503,32 @@ case $1 in
   ;;
 
   --restat)
+    if [ $# -gt 1 ]; then abort 'Invalid argument(s)'; fi;
+
+    print 'Resetting batterystats...';
     dumpsys batterystats --reset >/dev/null;
     rm -f /data/system/batterystats.bin;
     print --done;
   ;;
 
-  --reconfig) reconfigure --force; ;;
-
-  --reset)
-    disable_mcc_logs=true mcc --restat >/dev/null;
+  --reconfig)
+    if [ $# -gt 1 ]; then abort 'Invalid argument(s)'; fi;
     reconfigure --force;
   ;;
 
-  --info)
-    reconfigure;
+  --reset)
+    if [ $# -gt 1 ]; then abort 'Invalid argument(s)'; fi;
 
+    print 'Running [--restat] -> [--reconfig]...';
+    disable_mcc_logs=true skip_mcc_detach=true mcc --restat >/dev/null;
+    reconfigure --force >/dev/null;
+    print --done;
+  ;;
+
+  --info)
+    if [ $# -gt 1 ]; then abort 'Invalid argument(s)'; fi;
+
+    reconfigure;
     if (! is_charging); then
       chg_stat='Not charging';
     else
@@ -540,7 +553,7 @@ case $1 in
     echo -e 'Battery Information\n';
 
     echo "- Level : $(batt_level)";
-    echo "- Health: $(get_prop POWER_SUPPLY_HEALTH $(uevent_f))";
+    echo "- Health: $(get_event HEALTH)";
     echo -e "- Status: $chg_stat\n";
 
     echo -e 'Current Settings\n';
@@ -554,12 +567,14 @@ case $1 in
   ;;
 
   --help)
+    if [ $# -gt 1 ]; then abort 'Invalid argument(s)'; fi;
+
     head -n 5   $help_path;
-    head -n 176 $help_path | tail -n 155;
+    head -n 181 $help_path | tail -n 160;
   ;;
 
   *)
-    print --error 'No arguments given';
+    print --error 'Invalid argument(s)';
     disable_mcc_logs=true mcc --help;
   ;;
 esac;
