The first beta release candidate

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,57 +1,39 @@
 #!/sbin/sh
-# My Charging Controller
+# Battery Life Extender
 # JayminSuthar @ xda-developers
 
 # Copyright (c) 2018 Jaymin Suthar. All rights reserved.
 
-# This file is a part of "My Charging Controller (mcc)".
+# This file is a part of "Battery Life Extender (blex)".
 
-# mcc is released under the terms of the GNU GPL v3, as been
-## published by the Free Software Foundation. And permission
-## hereby is granted to use, modify or redistribute it maybe
-## partially or entirely under GPLv3 only.
+# blex is released under the GNU GPL v3 license as published
+# by the Free Software Foundation. And you hereby, are given
+# permission to use, modify or redistribute it either partly
+# or entirely, under v3 or any later version of the GPL.
 
-# mcc was written in a hope of being useful. And any kind of
-## warranty is not provided. See GPLv3 for details.
+# blex is provided to be useful, and no warranty, support or
+# fitness for a specific purpose is promised with it, and to
+# just not blame me for anything it caused, see the GPL.
 
-# You should already have received a copy of GPLv3 with mcc,
-## if not, see <http://www.gnu.org/licenses/>.
+# blex is always built with a copy of GPLv3 (COPYING) in the
+# top folder, if not see <http://www.gnu.org/licenses/>.
 
 out_fd=$2
 boot_mode=false
+magisk_mode=true
+de_data=/data/adb
 system=/system
-system_mode=false
-adb_dir=/data/adb
-tmp_dir=/dev/mcc_$$
+
+tmp_dir=/dev/blex_tmp
 zip_dir=$tmp_dir/zip
-bb_dir=$zip_dir/bin
-sys_dir=$zip_dir/system
-bin_path=$bb_dir/busybox
-copy_path=$zip_dir/COPYING
-help_path=$zip_dir/README.md
-conf_path=$zip_dir/mcc.conf
-
-umask 022
-exec 2>/dev/mcc_install.log
-set -x
-
-if echo "$(ps -A || ps)" | grep -v grep | grep zygote >/dev/null; then
-  boot_mode=true
-else
-  mount -o bind /dev/urandom /dev/random
-  fd_dir=/proc/$$/fd
-  if readlink $fd_dir/$2 | grep /tmp >/dev/null; then
-    for fd in $fd_dir/*; do
-      if readlink $fd | grep pipe >/dev/null; then
-        fd=${fd##*/}
-        if ps | grep -v grep | grep " 3 $fd " >/dev/null; then
-          out_fd=$fd
-          break
-        fi
-      fi
-    done
-  fi
-fi
+bin_dir=$zip_dir/bin
+zip_sys=$zip_dir/system
+cfg_file=$zip_dir/blex.cfg
+prop_file=$zip_dir/module.prop
+boot_exec=$zip_dir/post-fs-data.sh
+doc_file=$zip_dir/README.md
+gpl_file=$zip_dir/COPYING
+bb_exec=$bin_dir/busybox
 
 ui_print() {
   if ! $boot_mode; then
@@ -61,28 +43,19 @@ ui_print() {
   fi
 }
 
-abort() {
-  ui_print ' '
-  print --error "$1"
-  cleanup --error
-  exit 1
-}
-
 print() {
   case "$1" in
-    --done)  ui_print '- Done'      ;;
-    --error) ui_print "ERROR: $2"   ;;
-    --warn)  ui_print "WARNING: $2" ;;
-    --info)  ui_print "INFO: $2"    ;;
-    *)       ui_print "- $1"        ;;
+    --error) ui_print "ERROR: $2" ;;
+    --info)  ui_print "INFO: $2"  ;;
+    *)       ui_print "- $1"      ;;
   esac
 }
 
 cleanup() {
-  print 'Cleaning up temp'
 
-  if test "$1" == --error; then rm -r $mcc_dir $mcc_path $init_path; fi
-  if umount $mount_dir; then losetup -d $loop_path; fi
+  if umount $mount_path; then
+    losetup -d $loop_block
+  fi
   rm -r $tmp_dir
 
   if ! $boot_mode; then
@@ -92,13 +65,21 @@ cleanup() {
   fi
 }
 
+abort() {
+  print --error "$1"
+  cleanup
+  exit 1
+}
+
 is_mounted() {
   mount | grep -q " $1 "
 }
 
 mount_wrap() {
-  if ! mount -t auto -o $rw /$1; then
-    if ! mount -t auto -o $rw,remount /$1; then abort "Mounting /$1 failed."; fi
+  if ! mount -t auto -o $rw $1; then
+    if ! mount -t auto -o $rw,remount $1; then
+      abort "Failed to mount $1"
+    fi
   fi
 }
 
@@ -107,7 +88,16 @@ get_prop() {
 }
 
 set_prop() {
-  sed -i "s/^$1=.*/$1=$2/" $3
+  sed -i "s|^$1=.*|$1=$2|" $3
+}
+
+migrate_cfg() {
+  if test -f $1; then
+    print 'Migrating configurations'
+    for prop in auto_switch auto_power thr_disable thr_enable thr_power; do
+      set_prop $prop $(get_prop $prop $1) $cfg_file
+    done
+  fi
 }
 
 set_perm() {
@@ -130,177 +120,178 @@ set_perm_recursive() {
   done
 }
 
-restore_cfg() {
-  if cfg_path_bak=$(ls $tmp_dir/mcc.conf); then
-    print 'Migrating configs backup'
-    for prop in auto_switch auto_power thr_disable thr_enable thr_power; do
-      set_prop $prop $(get_prop $prop $cfg_path_bak) $cfg_path
-    done
-  fi
-}
+umask 077
+exec 2>/dev/blex_install.log
+set -x
+
+if ps | grep -v grep | grep zygote >/dev/null; then
+  boot_mode=true
+fi
 
 ui_print ' '
-ui_print '************************************************************'
-ui_print '                My Charging Controller (mcc)                '
-ui_print '************************************************************'
-ui_print '   Copyright (c) 2018 Jaymin Suthar. All rights reserved.   '
-ui_print '************************************************************'
-ui_print ' '
+ui_print '******************************************'
+ui_print '  Battery Life Extender (blex) Installer  '
+ui_print '******************************************'
 
-print 'Building common environment'
+print 'Preparing environment'
 
 mkdir -p $zip_dir
-unzip -o "$3" -d $zip_dir >/dev/null
-if ! chmod 0755 $bin_path; then
-  abort 'Unzipping files failed.'
-elif ! $bin_path --install $bb_dir/; then
-  abort 'Chipset is not supported.'
-fi
-export PATH=$bb_dir:$PATH
+unzip "$3" -d $zip_dir >/dev/null
 
-print 'Checking for systemless support'
-if ! is_mounted /data; then
-  if ! mount /data; then abort 'Mounting /data failed.'; fi
+if ! chmod 0755 $bb_exec; then
+  abort 'Failed to extract zip'
+elif ! $bb_exec --install $bin_dir/; then
+  abort 'Chipset is not supported'
 fi
-if test -d $adb_dir/magisk; then
+export PATH=$bin_dir:$PATH
+
+if ! is_mounted /data; then
+  if ! mount /data; then
+    abort 'Failed to mount /data'
+  fi
+fi
+
+print 'Checking for Magisk support'
+if test "$(get_prop MAGISK_VER_CODE $de_data/magisk/util_functions.sh)" -ge 1468; then
   rw=ro
 else
+  print --info 'Magisk is not detected, install in system mode'
+  magisk_mode=false
   rw=rw
-  system_mode=true
-
-  ui_print ' '
-  ui_print '************************************************************'
-  ui_print '         Systemless interface (Magisk) not detected         '
-  ui_print '************************************************************'
-  ui_print '        mcc will install in system mode, mount rw :(        '
-  ui_print '************************************************************'
-  ui_print ' '
 fi
 
-print 'Mounting required partitions'
-mount_wrap system
-if test -f /system/init.rc; then system=/system/system; fi
-if test -L $system/vendor; then mount_wrap vendor; fi
+print 'Mounting /system and /vendor'
+mount_wrap /system
+if test -f /system/init.rc; then
+  system=/system/system
+fi
+if test -L $system/vendor; then
+  mount_wrap /vendor
+fi
 
 if ! $boot_mode; then
-  if uname -m | grep -q arm64; then
-    export LD_LIBRARY_PATH=$system/lib64:$system/vendor/lib64
+  mount -o bind /dev/urandom /dev/random
+  if test -d $system/lib64; then
+    export LD_LIBRARY_PATH=$system/lib64:/vendor/lib64
   else
-    export LD_LIBRARY_PATH=$system/lib:$system/vendor/lib
+    export LD_LIBRARY_PATH=$system/lib:/vendor/lib
   fi
 fi
 
-if $system_mode; then
-  mcc_dir=$adb_dir/mcc
-  bin_dir=$mcc_dir/bin
-  doc_dir=$mcc_dir/docs
-  init_dir=$system/etc/init.d
-  bb_path=$bin_dir/busybox
-  cfg_path=$mcc_dir/mcc.conf
-  mcc_path=$system/xbin/mcc
-  init_path=$init_dir/mcc_launcher
+if $magisk_mode; then
+  blex_live=/sbin/.core/img/blex
+  img_path=$de_path/magisk.img
 
-  if test ! -d $init_dir; then
-    print --info 'Your device lacks init.d support, I recommend that you'
-    print --info 'try out Init.d Injector by @Zackptg5. This tool can be'
-    print --info 'found at XDA, search the forums :)'
-    abort 'init.d support not detected.'
+  mount_path=$tmp_dir/img
+  blex_dir=$mount_path/blex
+  sys_dir=$blex_dir/system
+  doc_dir=$blex_dir/docs
+  bin_dir=$blex_dir/bin
+
+  if $boot_mode; then
+    img_path=$de_data/magisk_merge.img
   fi
 
-  print --info 'Install started (system).'
-
-  print 'Initializing files and paths'
-  mv $cfg_path $tmp_dir/
-  rm -r $mcc_dir
-  mkdir -p $doc_dir $bin_dir $mcc_dir/log
-
-  print 'Copying files to destinations'
-  cp -rf $sys_dir/.            $system/
-  cp     $bin_path             $bin_dir/
-  cp     $conf_path            $mcc_dir/
-  cp     $copy_path $help_path $doc_dir/
-
-  restore_cfg
-
-  print 'Setting permissions of files'
-  set_perm_recursive $mcc_dir   0 0    0700 0600 u:object_r:adb_data_file:s0
-  set_perm           $bb_path   0 2000 0710      u:object_r:adb_data_file:s0
-  set_perm           $mcc_path  0 2000 0755
-  set_perm           $init_path 0 0    0755
-
-  print 'Giving a final touch'
-  $bb_path --install $bin_dir/
-
-else
-  mount_dir=$tmp_dir/img
-  mcc_dir=$mount_dir/mcc
-  bin_dir=$mcc_dir/bin
-  doc_dir=$mcc_dir/docs
-  xbin_dir=$mcc_dir/system/xbin
-  bb_path=$bin_dir/busybox
-  cfg_path=$mcc_dir/mcc.conf
-  img_path=$adb_dir/magisk.img
-  mcc_dir_live=/sbin/.core/img/mcc
-
-  if $boot_mode; then img_path=$adb_dir/magisk_merge.img; fi
-  if test ! -d $system/xbin; then xbin_dir=${xbin_dir%/*}/bin; fi
-
   if test ! -f $img_path; then
-    print "Creating a 64M $img_path"
+    print 'Creating ext4 image'
     if ! make_ext4fs -l 64M $img_path >/dev/null; then
       $system/bin/mke2fs -t ext4 $img_path 64M >/dev/null
     fi
   fi
 
-  mkdir $mount_dir
-  print "Mounting $img_path to $mount_dir"
-  for minor in 0 1 2 3 4 5 6 7; do
-    loop_path=/dev/block/loop$minor
+  print 'Mounting ext4 image'
 
-    if test ! -b $loop_path; then mknod $loop_path b 7 $minor; fi
-    if losetup $loop_path $img_path >/dev/null; then
-      if mount -t ext4 -o loop $loop_path $mount_dir; then break; fi
+  mkdir $mount_path
+  for minor in 0 1 2 3 4 5 6 7; do
+    loop_block=/dev/block/loop$minor
+
+    if test ! -b $loop_block; then
+      mknod $loop_block b 7 $minor
+    fi
+    if losetup $loop_block $img_path >/dev/null; then
+      if mount -t ext4 -o loop $loop_block $mount_path; then
+        break
+      fi
     fi
   done
-  if ! is_mounted $mount_dir; then abort 'Mounting image failed.'; fi
+  if ! is_mounted $mount_path; then
+    abort 'Failed to mount image'
+  fi
 
-  print --info 'Install started (systemless).'
-
-  print 'Initializing files and paths'
   if $boot_mode; then
-    cp $mcc_dir_live/mcc.conf $tmp_dir/
+    migrate_cfg $blex_live/blex.cfg
   else
-    cp $cfg_path $tmp_dir/
+    migrate_cfg $blex_dir/blex.cfg
   fi
-  rm -r $mcc_dir
-  mkdir -p $doc_dir $xbin_dir $bin_dir $mcc_dir/log
 
-  print 'Copying files to destinations'
-  cp -r $sys_dir/xbin/.                                          $xbin_dir/
-  cp    $bin_path                                                $bin_dir/
-  cp    $conf_path $zip_dir/post-fs-data.sh $zip_dir/module.prop $mcc_dir/
-  cp    $copy_path $help_path                                    $doc_dir/
+  print 'Preparing install folders'
+  rm -r $blex_dir
+  mkdir -p $sys_dir $bin_dir $doc_dir $blex_dir/log
 
-  restore_cfg
+  print 'Copying required blex files'
+  cp -r $zip_sys/.                      $sys_dir/
+  cp    $boot_exec $cfg_file $prop_file $blex_dir/
+  cp    $bb_exec                        $bin_dir/
+  cp    $doc_file                       $doc_dir/HELP
+  cp    $gpl_file                       $doc_dir/
 
-  print 'Setting permissions of files'
-  set_perm_recursive $mcc_dir  0 0    0755 0644
-  set_perm_recursive $xbin_dir 0 2000 0755 0755
-  set_perm           $bb_path  0 2000 0755
+  if test ! -d $system/xbin; then
+    mv $sys_dir/xbin $sys_dir/bin
+  fi
+  touch $blex_dir/auto_mount
 
-  print 'Giving a final touch'
-  touch $mcc_dir/auto_mount
+  print 'Setting permissions'
+  set_perm_recursive $blex_dir        0 0    0755 0644
+  set_perm_recursive $sys_dir/*       0 2000 0755 0755
+  set_perm           $bin_dir/busybox 0 2000 0755
+
   if $boot_mode; then
-    mkdir $mcc_dir_live
-    touch $mcc_dir_live/update
-    cp -f $mcc_dir/module.prop $mcc_dir_live/
+    mkdir $blex_live
+    touch $blex_live/update
+    cp -f $prop_file $blex_live/
   fi
-  $bb_path --install $bin_dir/
+else
+  blex_dir=$de_data/blex
+  doc_dir=$blex_dir/docs
+  bin_dir=$blex_dir/bin
+  log_dir=$blex_dir/log
+  init_dir=$system/etc/init.d
+  main_exec=$system/xbin/blex
+  init_exec=$init_dir/99blexd
+
+  if test ! -d $init_dir; then
+    abort 'Init.d support is not detected'
+  fi
+
+  migrate_cfg $blex_dir/blex.cfg
+
+  print 'Preparing install folders'
+  rm -r $blex_dir
+  mkdir -p $bin_dir $doc_dir $log_dir
+
+  print 'Copying required blex files'
+  cp -rf $zip_sys/. $system/
+  cp     $boot_exec $init_exec
+  cp     $bb_exec   $bin_dir/
+  cp     $cfg_file  $blex_dir/
+  cp     $prop_file $blex_dir/blex.prop
+  cp     $doc_file  $doc_dir/HELP
+  cp     $gpl_file  $doc_dir/
+
+  touch $log_dir/boot.log $log_dir/main.log
+
+  print 'Patching them for system mode'
+  set_prop blex_dir $blex_dir $main_exec
+  set_prop blex_dir $blex_dir $init_exec
+
+  print 'Setting permissions'
+  set_perm_recursive $blex_dir        0 0    0700 0600 u:object_r:adb_data_file:s0
+  set_perm           $bin_dir/busybox 0 2000 0710      u:object_r:adb_data_file:s0
+  set_perm           $main_exec       0 2000 0750
+  set_perm           $init_exec       0 0    0700
 fi
 
+print 'Cleaning up'
 cleanup
-print --warn 'mcc is installed! After rebooting, please configure'
-print --warn 'it by calling the configurator with `mcc --config`.'
-print --warn 'Otherwise, mcc will not work!'
-print --done
+print 'Done'
 exit 0
