Release version 'Redefined 1.1.2'

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -79,7 +79,7 @@ print() {
 }
 
 cleanup() {
-  print 'Cleaning'
+  print 'Cleaning up temp'
 
   if test "$1" == --error; then rm -r $mcc_dir $mcc_path $init_path; fi
   if umount $mount_dir; then losetup -d $loop_path; fi
@@ -98,7 +98,7 @@ is_mounted() {
 
 mount_wrap() {
   if ! mount -t auto -o $rw /$1; then
-    if ! mount -t auto -o $rw,remount /$1; then abort "Mounting /$1 failed"; fi
+    if ! mount -t auto -o $rw,remount /$1; then abort "Mounting /$1 failed."; fi
   fi
 }
 
@@ -147,19 +147,20 @@ ui_print '   Copyright (c) 2018 Jaymin Suthar. All rights reserved.   '
 ui_print '************************************************************'
 ui_print ' '
 
-print 'Building environment'
+print 'Building common environment'
 
+mkdir -p $zip_dir
 unzip -o "$3" -d $zip_dir >/dev/null
 if ! chmod 0755 $bin_path; then
-  abort 'Unzipping files failed'
+  abort 'Unzipping files failed.'
 elif ! $bin_path --install $bb_dir/; then
-  abort 'Chipset not supported'
+  abort 'Chipset is not supported.'
 fi
 export PATH=$bb_dir:$PATH
 
-print 'Checking systemless support'
+print 'Checking for systemless support'
 if ! is_mounted /data; then
-  if ! mount /data; then abort 'Mounting /data failed'; fi
+  if ! mount /data; then abort 'Mounting /data failed.'; fi
 fi
 if test -d $adb_dir/magisk; then
   rw=ro
@@ -176,7 +177,7 @@ else
   ui_print ' '
 fi
 
-print 'Mounting partitions'
+print 'Mounting required partitions'
 mount_wrap system
 if test -f /system/init.rc; then system=/system/system; fi
 if test -L $system/vendor; then mount_wrap vendor; fi
@@ -202,13 +203,13 @@ if $system_mode; then
   if test ! -d $init_dir; then
     print --info 'Your device lacks init.d support, I recommend that you'
     print --info 'try out Init.d Injector by @Zackptg5. This tool can be'
-    print --info 'found at XDA, search the forums.'
-    abort 'init.d support not detected'
+    print --info 'found at XDA, search the forums :)'
+    abort 'init.d support not detected.'
   fi
 
-  print --info 'Install start (system)'
+  print --info 'Install started (system).'
 
-  print 'Initializing files/paths'
+  print 'Initializing files and paths'
   mv $cfg_path $tmp_dir/
   rm -r $mcc_dir
   mkdir -p $doc_dir $bin_dir $mcc_dir/log
@@ -221,13 +222,13 @@ if $system_mode; then
 
   restore_cfg
 
-  print 'Setting permissions'
+  print 'Setting permissions of files'
   set_perm_recursive $mcc_dir   0 0    0700 0600 u:object_r:adb_data_file:s0
   set_perm           $bb_path   0 2000 0710      u:object_r:adb_data_file:s0
   set_perm           $mcc_path  0 2000 0755
   set_perm           $init_path 0 0    0755
 
-  print 'Finalizing install'
+  print 'Giving a final touch'
   $bb_path --install $bin_dir/
 
 else
@@ -245,14 +246,14 @@ else
   if test ! -d $system/xbin; then xbin_dir=${xbin_dir%/*}/bin; fi
 
   if test ! -f $img_path; then
-    print "Creating $img_path"
+    print "Creating a 64M $img_path"
     if ! make_ext4fs -l 64M $img_path >/dev/null; then
       $system/bin/mke2fs -t ext4 $img_path 64M >/dev/null
     fi
   fi
 
   mkdir $mount_dir
-  print "Mounting $img_path to temp"
+  print "Mounting $img_path to $mount_dir"
   for minor in 0 1 2 3 4 5 6 7; do
     loop_path=/dev/block/loop$minor
 
@@ -261,11 +262,11 @@ else
       if mount -t ext4 -o loop $loop_path $mount_dir; then break; fi
     fi
   done
-  if ! is_mounted $mount_dir; then abort 'Mounting image failed'; fi
+  if ! is_mounted $mount_dir; then abort 'Mounting image failed.'; fi
 
-  print --info 'Install start (systemless)'
+  print --info 'Install started (systemless).'
 
-  print 'Initializing files/paths'
+  print 'Initializing files and paths'
   if $boot_mode; then
     cp $mcc_dir_live/mcc.conf $tmp_dir/
   else
@@ -282,12 +283,12 @@ else
 
   restore_cfg
 
-  print 'Setting permissions'
+  print 'Setting permissions of files'
   set_perm_recursive $mcc_dir  0 0    0755 0644
   set_perm_recursive $xbin_dir 0 2000 0755 0755
   set_perm           $bb_path  0 2000 0755
 
-  print 'Finalizing install'
+  print 'Giving a final touch'
   touch $mcc_dir/auto_mount
   if $boot_mode; then
     mkdir $mcc_dir_live
@@ -298,8 +299,8 @@ else
 fi
 
 cleanup
-print --warn 'Done installing. After rebooting, you must call the'
-print --warn 'configurator by `mcc --config` to configure mcc. If'
-print --warn 'not, mcc will not work!'
+print --warn 'mcc is installed! After rebooting, please configure'
+print --warn 'it by calling the configurator with `mcc --config`.'
+print --warn 'Otherwise, mcc will not work!'
 print --done
 exit 0
diff --git a/system/xbin/mcc b/system/xbin/mcc
--- a/system/xbin/mcc
+++ b/system/xbin/mcc
@@ -41,13 +41,13 @@ print() {
 }
 
 if ! id | grep uid=0 >/dev/null; then
-  abort 'Run `su` first and then mcc'
+  abort 'Please run `su` first and then mcc.'
 elif test ! -d $mcc_dir || test ! -x $bin_dir/awk; then
-  abort 'There was an internal error'
+  abort 'Internal error occured, please report.'
 elif test -f $mcc_dir/.lock; then
   echo
   print --error "Due to some safety reasons, you can't execute mcc for"
-  print --error '120 seconds after booting, wait softly until then.'
+  print --error '120 seconds after booting, please wait until then.'
   exit
 fi
 
@@ -123,12 +123,12 @@ is_charging() {
 
 is_belonging() {
   if test $1 -lt $2 || test $1 -gt $3; then
-    abort "$1 does not belong to $2-$3"
+    abort "$1 does not belong to $2-$3."
   fi
 }
 
 is_level() {
-  if ! echo $1 | grep -Eq '^[0-9]+$'; then abort "$1 is not a number"; fi
+  if ! echo $1 | grep -Eq '^[0-9]+$'; then abort "$1 is not a number."; fi
   is_belonging $1 1 99
 }
 
@@ -180,9 +180,9 @@ toggle() {
     stat_new=ON
 
     if ! is_runningd; then
-      abort 'The mcc daemon is not running'
+      abort 'The mcc daemon is not running.'
     elif ! reconfigure; then
-      abort 'Low level configuration failed'
+      abort 'Low level configuration failed.'
     fi
   fi
   print "Toggling $2 $stat_new"
@@ -198,16 +198,16 @@ charge() {
   text=${key_init}d
 
   if ! is_runningd; then
-    abort 'The mcc daemon is not running'
+    abort 'The mcc daemon is not running.'
   elif test $(switch_do) != default; then
-    abort 'Another task is already running'
+    abort 'Another task is already running.'
   elif ! reconfigure; then
-    abort 'Low level configuration failed'
+    abort 'Low level configuration failed.'
   fi
 
   print --warn 'Manual methods are for advanced users only, without'
-  print --warn 'the mathematics regarding battery life, remember it'
-  print --warn '(the math) before operating on it.'
+  print --warn 'the math regarding battery life, please remember a'
+  print --warn 'before operating on it.'
 
   print 'Parsing argument'
   if echo $2 | grep -Eq '^[0-9]+%$'; then
@@ -234,7 +234,7 @@ charge() {
     sleep $2
 
   else
-    abort "Invalid format: $2"
+    abort "Invalid format: $2."
   fi
   print 'Freeing the daemon'
   set_prop switch_do default
@@ -262,7 +262,7 @@ reconfigure() {
   for i in 1 2; do set_prop switch_$i dummySwitch; done
 
   print --warn 'Configurator requires the device to be charging, is'
-  print --warn 'it charging right now ?? press enter when ready.'
+  print --warn 'it charging right now ?? Press enter when ready.'
   read i
 
   print 'Configuring mcc at kernel/driver level'
@@ -347,11 +347,11 @@ echo
 
 if test "$1" == --force; then
   if ! echo "$2" | grep -Eq '^(--switch|--power)$'; then
-    abort 'Invalid argument(s)'
+    abort 'Invalid argument(s).'
   fi
   print --warn 'Forcing thresholds outside set boundaries is unsafe'
-  print --warn 'and all upto you. mcc did the math, but was skipped'
-  print --warn 'by you.'
+  print --warn 'and all upto you. mcc did the math, but you skipped'
+  print --warn 'that :('
   enforce=true
   shift
 fi
@@ -387,14 +387,14 @@ case $1 in
       is_level $3
 
       if test $2 -le $3; then
-        abort "$2 is not greater than $3"
+        abort "$2 is not greater than $3."
       elif ! $enforce; then
         is_belonging $2 15 85
         is_belonging $3 15 85
-        if test $2 -lt $(($3 + 5)); then abort "$2 is too close to $3"; fi
+        if test $2 -lt $(($3 + 5)); then abort "$2 is too close to $3."; fi
       fi
     else
-      abort 'Invalid argument(s)'
+      abort 'Invalid argument(s).'
     fi
 
     print "Updating 'thr_disable', 'thr_enable'"
@@ -404,7 +404,7 @@ case $1 in
   ;;
 
   --power)
-    if test $# -ne 2; then abort 'Invalid argument(s)'; fi
+    if test $# -ne 2; then abort 'Invalid argument(s).'; fi
 
     print 'Validating argument'
     is_level $2
@@ -416,7 +416,7 @@ case $1 in
   ;;
 
   --revert)
-    if test $# -gt 1; then abort 'Invalid argument(s)'; fi
+    if test $# -gt 1; then abort 'Invalid argument(s).'; fi
 
     print 'Reverting Automation thresholds'
     set_prop thr_disable 80
@@ -434,9 +434,9 @@ case $1 in
       --revert)
 
         if ! is_runningd; then
-          abort 'The mcc daemon is not running'
+          abort 'The mcc daemon is not running.'
         elif ! reconfigure; then
-          abort 'Low level configuration failed'
+          abort 'Low level configuration failed.'
         fi
 
         print 'Reverting Automation features'
@@ -444,28 +444,28 @@ case $1 in
         set_prop auto_power  true
         print --done
       ;;
-      *) abort 'Invalid argument(s)' ;;
+      *) abort 'Invalid argument(s).' ;;
     esac
   ;;
 
   --enable)
-    if test $# -ne 2; then abort 'Invalid argument(s)'; fi
+    if test $# -ne 2; then abort 'Invalid argument(s).'; fi
     charge --enable $2
   ;;
 
   --disable)
-    if test $# -ne 2; then abort 'Invalid argument(s)'; fi
+    if test $# -ne 2; then abort 'Invalid argument(s).'; fi
     charge --disable $2
   ;;
 
   --cleanup)
-    if test $# -gt 1; then abort 'Invalid argument(s)'; fi
+    if test $# -gt 1; then abort 'Invalid argument(s).'; fi
 
-    print --warn '[--cleanup] kills the mcc daemon, you must start it'
-    print --warn 'again using [--ckdaemon] afterwards.'
+    print --warn '[--cleanup] kills the mcc daemon, please start that'
+    print --warn 'again manually by [--ckdaemon] afterwards.'
 
 
-    print 'Cleaning up'
+    print 'Cleaning up mcc instances'
     for pid in $(ps | grep -v grep | grep '{mcc}' | grep -v $$ | awk '{ print $1 }'); do
       kill -9 $pid
     done
@@ -474,18 +474,18 @@ case $1 in
   ;;
 
   --ckdaemon)
-    if test $# -gt 1; then abort 'Invalid argument(s)'; fi
+    if test $# -gt 1; then abort 'Invalid argument(s).'; fi
 
     if is_runningd; then
-      abort 'The mcc daemon is already there'
+      abort 'The mcc daemon is already there.'
     elif ! reconfigure; then
-      abort 'Low level configuration failed'
+      abort 'Low level configuration failed.'
     fi
 
     print 'Starting the mcc daemon'
     skip_mcc_logs=true mcc --launch-daemon </dev/null >/dev/null 2>&1
     sleep 0.1
-    if ! is_runningd; then abort 'Starting the daemon failed'; fi
+    if ! is_runningd; then abort 'Starting the daemon failed.'; fi
     print --done
   ;;
 
@@ -494,8 +494,8 @@ case $1 in
     revert=false
     stat_saved=default
 
-    if test $# -gt 1; then abort 'Invalid argument(s)'; fi
-    if is_runningd; then abort 'Another daemon instance already exists'; fi
+    if test $# -gt 1; then abort 'Invalid argument(s).'; fi
+    if is_runningd; then abort 'Another daemon instance already exists.'; fi
 
     while true; do
       while ! reconfigure --no-action; do sleep 0.1; done
@@ -540,9 +540,9 @@ case $1 in
   ;;
 
   --restat)
-    if test $# -gt 1; then abort 'Invalid argument(s)'; fi
+    if test $# -gt 1; then abort 'Invalid argument(s).'; fi
 
-    print --warn '[--restat] might not work for all devices.'
+    print --warn '[--restat] might not work for all devices :('
 
     print 'Resetting batterystats'
     dumpsys batterystats --reset >/dev/null
@@ -551,22 +551,22 @@ case $1 in
   ;;
 
   --config)
-    if test $# -gt 1; then abort 'Invalid argument(s)'; fi
-    if ! reconfigure --force; then abort 'Low level configuration failed'; fi
+    if test $# -gt 1; then abort 'Invalid argument(s).'; fi
+    if ! reconfigure --force; then abort 'Low level configuration failed.'; fi
   ;;
 
   --reset)
-    if test $# -gt 1; then abort 'Invalid argument(s)'; fi
+    if test $# -gt 1; then abort 'Invalid argument(s).'; fi
 
     skip_mcc_logs=true skip_mcc_detach=true mcc --restat
-    if ! reconfigure --force; then abort 'Low level configuration failed'; fi
+    if ! reconfigure --force; then abort 'Low level configuration failed.'; fi
     print --done
   ;;
 
   --info)
-    if test $# -gt 1; then abort 'Invalid argument(s)'; fi
+    if test $# -gt 1; then abort 'Invalid argument(s).'; fi
 
-    if ! reconfigure; then abort 'Low level configuration failed'; fi
+    if ! reconfigure; then abort 'Low level configuration failed.'; fi
     if ! is_charging; then
       chg_stat='Not charging'
     else
@@ -605,14 +605,14 @@ case $1 in
   ;;
 
   --help)
-    if test $# -gt 1; then abort 'Invalid argument(s)'; fi
+    if test $# -gt 1; then abort 'Invalid argument(s).'; fi
 
     head -n 4   $help_path
     head -n 197 $help_path | tail -n 177
   ;;
 
   *)
-    print --error 'No valid argument supplied, let mcc help a little'
+    print --error 'No valid argument supplied, let mcc help out a bit...'
     skip_mcc_logs=true mcc --help
   ;;
 esac
